### ISSUE TITLE
I didn't see any command related to IntactKV

### ISSUE THREAD

**Issue by LiMa-cas** [ruikangliu/IntactKV#1]
how to get the quantized model with IntactKV_[B] and awq together？

**Comment by ruikangliu** [comment]
Hi, IntactKV_[B] does not require any training, so you can directly run the evaluation shell script to get the evaluation results following commands in README. e.g. 

```
# evaluate w3g128 AWQ-quantized LLaMA-2-7B model on GPU0, port 29500
bash ./scripts/eval/eval.sh llama-2 7b awq 3 16 ppl 29500 0
```

[intactkv_eval.py](https://github.com/ruikangliu/IntactKV/blob/main/intactkv_eval.py) provides the code for incorporating IntactKV into AWQ pseudo-quantized model.

**Comment by LiMa-cas** [comment]
Thanks a lot!!! So how can I use the IntactKV to get a inference script for AWQ?

**Comment by ruikangliu** [comment]
Certainly, inference scripts are in `./scripts/eval`.

**Comment by LiMa-cas** [comment]
Hi，I see intackv_eval.py need the fp16 model. If I want to improve awq - 4bit quantized model , is it possbile to use intact_kv without fp16 model?
