### ISSUE TITLE
import fast_hadamard_transform

### ISSUE THREAD

**Issue by fangtiansheng11** [ruikangliu/IntactKV#3]
When I import fast_hadamard_transform, pycharm hinted me with the following info:
RuntimeError:
      The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.
At that time, my CUDA's version is 11.8 and my torch version is 2.4.1+cu121
Could you please be kindly provide some methods to solve it?

**Comment by ruikangliu** [comment]
`fast_hadamard_transform ` is needed for QuaRot. Maybe upgrade your CUDA version or downgrade torch version can help. You may also refer to this repo for more information [https://github.com/Dao-AILab/fast-hadamard-transform](https://github.com/Dao-AILab/fast-hadamard-transform).
